---

- name: "extract artifact."
  unarchive:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/

- name: "stop."
  shell: pm2 stop default
  ignore_errors: yes

- name: "start."
  environment: 
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}" 
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}" 
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}" 
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}" 
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}" 
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_ENTITIES: "./src/modules/**/*.entity.ts"
    TYPEORM_MIGRATIONS: "./src/migrations/*.ts"
  shell: |
    npm install
    pm2 start npm -- start